/**
 * @About
 * 
  */




//Lodaing types
export const IS_LOADING_START = "IS_LOADING_START";
export const IS_LOADING_STOP = "IS_LOADING_STOP";

//Employee
export const GET_EMPLOYEE_DATA_SUCCESS='GET_EMPLOYEE_DATA_SUCCESS';
export const  GET_EMPLOYEE_DATA_FAILED='GET_EMPLOYEE_DATA_FAILED'; 
export const ADD_EMPLOYEE_SUCCESS='ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILED='ADD_EMPLOYEE_FAILED';
export const EDIT_EMPOYEE_SUCCESS="EDIT_EMPOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILED="EDIT_EMPLOYEE_FAILED";
